distributors:
  configuration:
    - displayName: "OOO Алматерра"
      sheetTitle: "основной прайс"
      markers:
        - row: 1
          column: A
          text: "ООО \"АЛМАТЕРРА\""
        - row: 3
          column: A
          text: "штрих-код"
      firstContentRow: 4
      columnSpecification:
        id: A
        barcode: B
        name: C
        description: D
        vendor: E
        country:
        region:
        cellar:
        year: F
        date:
        color: G
        sweetness: H
        soilType:
        vintage:
        ranking:
        grapeType:
        capacity: I
        alcohol: J
        klass: K
        stock:
        price: L
#    - displayName: "OOO Алматерра"
#      sheetTitle: "основной прайс"
#      markers:
#        - row: 1
#          column: A
#          text: "OOO Алматерра"
#        - row: 2
#          column: A
#          text: "штрих-код"
#      firstContentRow: 4
#      columnSpecification:
#        id: A
#        barcode: B
#        name: C
#        description: D
#        vendor: E
#        country:
#        region:
#        cellar:
#        year: F
#        date:
#        color: G
#        sweetness: H
#        soilType:
#        vintage:
#        ranking:
#        grapeType:
#        capacity: I
#        alcohol: J
#        klass: K
#        stock:
#        price: L
